In [71]:
import numpy as np
import pandas as pd

In [72]:
# check the version of numpy and pandas
print(f"Numpy version : {np.__version__}")
print(f"Pandas version : {pd.__version__}")

Numpy version : 2.3.2
Pandas version : 2.3.1

In [73]:
movies = pd.read_csv(r"datasets\tmdb_5000_movies.csv")
credits = pd.read_csv(r"datasets\tmdb_5000_credits.csv")

In [74]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [75]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [76]:
movies = movies.merge(credits, on='title')

In [77]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [78]:
# Columns useful : genres, id, keywords, title, overview, cast, crew
# also we can add  release_date, runtime etc

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [79]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [80]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [81]:
movies.dropna(inplace=True)

In [82]:
movies.duplicated().sum()

np.int64(0)

In [83]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [84]:
# '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#  ['Action'.'Adventure','Fantasy','SciFi']

In [85]:
import ast
def convert(obj):
    obj = ast.literal_eval(obj)
    l = []
    for i in obj:
        l.append(i['name'])
    return l

In [ ]:
 
movies['genres'] = movies['genres'].apply(convert)

In [87]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [88]:
movies.iloc[0].keywords

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [89]:
movies['keywords'] = movies['keywords'].apply(convert)

In [90]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [91]:
for d in ast.literal_eval(movies.iloc[0].cast):
    print(d)

{'cast_id': 242, 'character': 'Jake Sully', 'credit_id': '5602a8a7c3a3685532001c9a', 'gender': 2, 'id': 65731, 'name': 'Sam Worthington', 'order': 0}
{'cast_id': 3, 'character': 'Neytiri', 'credit_id': '52fe48009251416c750ac9cb', 'gender': 1, 'id': 8691, 'name': 'Zoe Saldana', 'order': 1}
{'cast_id': 25, 'character': 'Dr. Grace Augustine', 'credit_id': '52fe48009251416c750aca39', 'gender': 1, 'id': 10205, 'name': 'Sigourney Weaver', 'order': 2}
{'cast_id': 4, 'character': 'Col. Quaritch', 'credit_id': '52fe48009251416c750ac9cf', 'gender': 2, 'id': 32747, 'name': 'Stephen Lang', 'order': 3}
{'cast_id': 5, 'character': 'Trudy Chacon', 'credit_id': '52fe48009251416c750ac9d3', 'gender': 1, 'id': 17647, 'name': 'Michelle Rodriguez', 'order': 4}
{'cast_id': 8, 'character': 'Selfridge', 'credit_id': '52fe48009251416c750ac9e1', 'gender': 2, 'id': 1771, 'name': 'Giovanni Ribisi', 'order': 5}
{'cast_id': 7, 'character': 'Norm Spellman', 'credit_id': '52fe48009251416c750ac9dd', 'gender': 2, 'id': 59231, 'name': 'Joel David Moore', 'order': 6}
{'cast_id': 9, 'character': 'Moat', 'credit_id': '52fe48009251416c750ac9e5', 'gender': 1, 'id': 30485, 'name': 'CCH Pounder', 'order': 7}
{'cast_id': 11, 'character': 'Eytukan', 'credit_id': '52fe48009251416c750ac9ed', 'gender': 2, 'id': 15853, 'name': 'Wes Studi', 'order': 8}
{'cast_id': 10, 'character': "Tsu'Tey", 'credit_id': '52fe48009251416c750ac9e9', 'gender': 2, 'id': 10964, 'name': 'Laz Alonso', 'order': 9}
{'cast_id': 12, 'character': 'Dr. Max Patel', 'credit_id': '52fe48009251416c750ac9f1', 'gender': 2, 'id': 95697, 'name': 'Dileep Rao', 'order': 10}
{'cast_id': 13, 'character': 'Lyle Wainfleet', 'credit_id': '52fe48009251416c750ac9f5', 'gender': 2, 'id': 98215, 'name': 'Matt Gerald', 'order': 11}
{'cast_id': 32, 'character': 'Private Fike', 'credit_id': '52fe48009251416c750aca5b', 'gender': 2, 'id': 154153, 'name': 'Sean Anthony Moran', 'order': 12}
{'cast_id': 33, 'character': 'Cryo Vault Med Tech', 'credit_id': '52fe48009251416c750aca5f', 'gender': 2, 'id': 397312, 'name': 'Jason Whyte', 'order': 13}
{'cast_id': 34, 'character': 'Venture Star Crew Chief', 'credit_id': '52fe48009251416c750aca63', 'gender': 2, 'id': 42317, 'name': 'Scott Lawrence', 'order': 14}
{'cast_id': 35, 'character': 'Lock Up Trooper', 'credit_id': '52fe48009251416c750aca67', 'gender': 2, 'id': 986734, 'name': 'Kelly Kilgour', 'order': 15}
{'cast_id': 36, 'character': 'Shuttle Pilot', 'credit_id': '52fe48009251416c750aca6b', 'gender': 0, 'id': 1207227, 'name': 'James Patrick Pitt', 'order': 16}
{'cast_id': 37, 'character': 'Shuttle Co-Pilot', 'credit_id': '52fe48009251416c750aca6f', 'gender': 0, 'id': 1180936, 'name': 'Sean Patrick Murphy', 'order': 17}
{'cast_id': 38, 'character': 'Shuttle Crew Chief', 'credit_id': '52fe48009251416c750aca73', 'gender': 2, 'id': 1019578, 'name': 'Peter Dillon', 'order': 18}
{'cast_id': 39, 'character': 'Tractor Operator / Troupe', 'credit_id': '52fe48009251416c750aca77', 'gender': 0, 'id': 91443, 'name': 'Kevin Dorman', 'order': 19}
{'cast_id': 40, 'character': 'Dragon Gunship Pilot', 'credit_id': '52fe48009251416c750aca7b', 'gender': 2, 'id': 173391, 'name': 'Kelson Henderson', 'order': 20}
{'cast_id': 41, 'character': 'Dragon Gunship Gunner', 'credit_id': '52fe48009251416c750aca7f', 'gender': 0, 'id': 1207236, 'name': 'David Van Horn', 'order': 21}
{'cast_id': 42, 'character': 'Dragon Gunship Navigator', 'credit_id': '52fe48009251416c750aca83', 'gender': 0, 'id': 215913, 'name': 'Jacob Tomuri', 'order': 22}
{'cast_id': 43, 'character': 'Suit #1', 'credit_id': '52fe48009251416c750aca87', 'gender': 0, 'id': 143206, 'name': 'Michael Blain-Rozgay', 'order': 23}
{'cast_id': 44, 'character': 'Suit #2', 'credit_id': '52fe48009251416c750aca8b', 'gender': 2, 'id': 169676, 'name': 'Jon Curry', 'order': 24}
{'cast_id': 46, 'character': 'Ambient Room Tech', 'credit_id': '52fe48009251416c750aca8f', 'gender': 0, 'id': 1048610, 'name': 'Luke Hawker', 'order': 25}
{'cast_id': 47, 'character': 'Ambient Room Tech / Troupe', 'credit_id': '52fe48009251416c750aca93', 'gender': 0, 'id': 42288, 'name': 'Woody Schultz', 'order': 26}
{'cast_id': 48, 'character': 'Horse Clan Leader', 'credit_id': '52fe48009251416c750aca97', 'gender': 2, 'id': 68278, 'name': 'Peter Mensah', 'order': 27}
{'cast_id': 49, 'character': 'Link Room Tech', 'credit_id': '52fe48009251416c750aca9b', 'gender': 0, 'id': 1207247, 'name': 'Sonia Yee', 'order': 28}
{'cast_id': 50, 'character': 'Basketball Avatar / Troupe', 'credit_id': '52fe48009251416c750aca9f', 'gender': 1, 'id': 1207248, 'name': 'Jahnel Curfman', 'order': 29}
{'cast_id': 51, 'character': 'Basketball Avatar', 'credit_id': '52fe48009251416c750acaa3', 'gender': 0, 'id': 89714, 'name': 'Ilram Choi', 'order': 30}
{'cast_id': 52, 'character': "Na'vi Child", 'credit_id': '52fe48009251416c750acaa7', 'gender': 0, 'id': 1207249, 'name': 'Kyla Warren', 'order': 31}
{'cast_id': 53, 'character': 'Troupe', 'credit_id': '52fe48009251416c750acaab', 'gender': 0, 'id': 1207250, 'name': 'Lisa Roumain', 'order': 32}
{'cast_id': 54, 'character': 'Troupe', 'credit_id': '52fe48009251416c750acaaf', 'gender': 1, 'id': 83105, 'name': 'Debra Wilson', 'order': 33}
{'cast_id': 57, 'character': 'Troupe', 'credit_id': '52fe48009251416c750acabb', 'gender': 0, 'id': 1207253, 'name': 'Chris Mala', 'order': 34}
{'cast_id': 55, 'character': 'Troupe', 'credit_id': '52fe48009251416c750acab3', 'gender': 0, 'id': 1207251, 'name': 'Taylor Kibby', 'order': 35}
{'cast_id': 56, 'character': 'Troupe', 'credit_id': '52fe48009251416c750acab7', 'gender': 0, 'id': 1207252, 'name': 'Jodie Landau', 'order': 36}
{'cast_id': 58, 'character': 'Troupe', 'credit_id': '52fe48009251416c750acabf', 'gender': 0, 'id': 1207254, 'name': 'Julie Lamm', 'order': 37}
{'cast_id': 59, 'character': 'Troupe', 'credit_id': '52fe48009251416c750acac3', 'gender': 0, 'id': 1207257, 'name': 'Cullen B. Madden', 'order': 38}
{'cast_id': 60, 'character': 'Troupe', 'credit_id': '52fe48009251416c750acac7', 'gender': 0, 'id': 1207259, 'name': 'Joseph Brady Madden', 'order': 39}
{'cast_id': 61, 'character': 'Troupe', 'credit_id': '52fe48009251416c750acacb', 'gender': 0, 'id': 1207262, 'name': 'Frankie Torres', 'order': 40}
{'cast_id': 62, 'character': 'Troupe', 'credit_id': '52fe48009251416c750acacf', 'gender': 1, 'id': 1158600, 'name': 'Austin Wilson', 'order': 41}
{'cast_id': 63, 'character': 'Troupe', 'credit_id': '52fe48019251416c750acad3', 'gender': 1, 'id': 983705, 'name': 'Sara Wilson', 'order': 42}
{'cast_id': 64, 'character': 'Troupe', 'credit_id': '52fe48019251416c750acad7', 'gender': 0, 'id': 1207263, 'name': 'Tamica Washington-Miller', 'order': 43}
{'cast_id': 65, 'character': 'Op Center Staff', 'credit_id': '52fe48019251416c750acadb', 'gender': 1, 'id': 1145098, 'name': 'Lucy Briant', 'order': 44}
{'cast_id': 66, 'character': 'Op Center Staff', 'credit_id': '52fe48019251416c750acadf', 'gender': 2, 'id': 33305, 'name': 'Nathan Meister', 'order': 45}
{'cast_id': 67, 'character': 'Op Center Staff', 'credit_id': '52fe48019251416c750acae3', 'gender': 0, 'id': 1207264, 'name': 'Gerry Blair', 'order': 46}
{'cast_id': 68, 'character': 'Op Center Staff', 'credit_id': '52fe48019251416c750acae7', 'gender': 2, 'id': 33311, 'name': 'Matthew Chamberlain', 'order': 47}
{'cast_id': 69, 'character': 'Op Center Staff', 'credit_id': '52fe48019251416c750acaeb', 'gender': 0, 'id': 1207265, 'name': 'Paul Yates', 'order': 48}
{'cast_id': 70, 'character': 'Op Center Duty Officer', 'credit_id': '52fe48019251416c750acaef', 'gender': 0, 'id': 1207266, 'name': 'Wray Wilson', 'order': 49}
{'cast_id': 71, 'character': 'Op Center Staff', 'credit_id': '52fe48019251416c750acaf3', 'gender': 2, 'id': 54492, 'name': 'James Gaylyn', 'order': 50}
{'cast_id': 72, 'character': 'Dancer', 'credit_id': '52fe48019251416c750acaf7', 'gender': 0, 'id': 1207267, 'name': 'Melvin Leno Clark III', 'order': 51}
{'cast_id': 73, 'character': 'Dancer', 'credit_id': '52fe48019251416c750acafb', 'gender': 0, 'id': 1207268, 'name': 'Carvon Futrell', 'order': 52}
{'cast_id': 74, 'character': 'Dancer', 'credit_id': '52fe48019251416c750acaff', 'gender': 0, 'id': 1207269, 'name': 'Brandon Jelkes', 'order': 53}
{'cast_id': 75, 'character': 'Dancer', 'credit_id': '52fe48019251416c750acb03', 'gender': 0, 'id': 1207270, 'name': 'Micah Moch', 'order': 54}
{'cast_id': 76, 'character': 'Dancer', 'credit_id': '52fe48019251416c750acb07', 'gender': 0, 'id': 1207271, 'name': 'Hanniyah Muhammad', 'order': 55}
{'cast_id': 77, 'character': 'Dancer', 'credit_id': '52fe48019251416c750acb0b', 'gender': 0, 'id': 1207272, 'name': 'Christopher Nolen', 'order': 56}
{'cast_id': 78, 'character': 'Dancer', 'credit_id': '52fe48019251416c750acb0f', 'gender': 0, 'id': 1207273, 'name': 'Christa Oliver', 'order': 57}
{'cast_id': 79, 'character': 'Dancer', 'credit_id': '52fe48019251416c750acb13', 'gender': 0, 'id': 1207274, 'name': 'April Marie Thomas', 'order': 58}
{'cast_id': 80, 'character': 'Dancer', 'credit_id': '52fe48019251416c750acb17', 'gender': 0, 'id': 1207275, 'name': 'Bravita A. Threatt', 'order': 59}
{'cast_id': 81, 'character': 'Mining Chief (uncredited)', 'credit_id': '52fe48019251416c750acb1b', 'gender': 0, 'id': 1207276, 'name': 'Colin Bleasdale', 'order': 60}
{'cast_id': 82, 'character': 'Veteran Miner (uncredited)', 'credit_id': '52fe48019251416c750acb1f', 'gender': 0, 'id': 107969, 'name': 'Mike Bodnar', 'order': 61}
{'cast_id': 83, 'character': 'Richard (uncredited)', 'credit_id': '52fe48019251416c750acb23', 'gender': 0, 'id': 1207278, 'name': 'Matt Clayton', 'order': 62}
{'cast_id': 84, 'character': "Nav'i (uncredited)", 'credit_id': '52fe48019251416c750acb27', 'gender': 1, 'id': 147898, 'name': 'Nicole Dionne', 'order': 63}
{'cast_id': 85, 'character': 'Trooper (uncredited)', 'credit_id': '52fe48019251416c750acb2b', 'gender': 0, 'id': 1207280, 'name': 'Jamie Harrison', 'order': 64}
{'cast_id': 86, 'character': 'Trooper (uncredited)', 'credit_id': '52fe48019251416c750acb2f', 'gender': 0, 'id': 1207281, 'name': 'Allan Henry', 'order': 65}
{'cast_id': 87, 'character': 'Ground Technician (uncredited)', 'credit_id': '52fe48019251416c750acb33', 'gender': 2, 'id': 1207282, 'name': 'Anthony Ingruber', 'order': 66}
{'cast_id': 88, 'character': 'Flight Crew Mechanic (uncredited)', 'credit_id': '52fe48019251416c750acb37', 'gender': 0, 'id': 1207283, 'name': 'Ashley Jeffery', 'order': 67}
{'cast_id': 14, 'character': 'Samson Pilot', 'credit_id': '52fe48009251416c750ac9f9', 'gender': 0, 'id': 98216, 'name': 'Dean Knowsley', 'order': 68}
{'cast_id': 89, 'character': 'Trooper (uncredited)', 'credit_id': '52fe48019251416c750acb3b', 'gender': 0, 'id': 1201399, 'name': 'Joseph Mika-Hunt', 'order': 69}
{'cast_id': 90, 'character': 'Banshee (uncredited)', 'credit_id': '52fe48019251416c750acb3f', 'gender': 0, 'id': 236696, 'name': 'Terry Notary', 'order': 70}
{'cast_id': 91, 'character': 'Soldier (uncredited)', 'credit_id': '52fe48019251416c750acb43', 'gender': 0, 'id': 1207287, 'name': 'Kai Pantano', 'order': 71}
{'cast_id': 92, 'character': 'Blast Technician (uncredited)', 'credit_id': '52fe48019251416c750acb47', 'gender': 0, 'id': 1207288, 'name': 'Logan Pithyou', 'order': 72}
{'cast_id': 93, 'character': 'Vindum Raah (uncredited)', 'credit_id': '52fe48019251416c750acb4b', 'gender': 0, 'id': 1207289, 'name': 'Stuart Pollock', 'order': 73}
{'cast_id': 94, 'character': 'Hero (uncredited)', 'credit_id': '52fe48019251416c750acb4f', 'gender': 0, 'id': 584868, 'name': 'Raja', 'order': 74}
{'cast_id': 95, 'character': 'Ops Centreworker (uncredited)', 'credit_id': '52fe48019251416c750acb53', 'gender': 0, 'id': 1207290, 'name': 'Gareth Ruck', 'order': 75}
{'cast_id': 96, 'character': 'Engineer (uncredited)', 'credit_id': '52fe48019251416c750acb57', 'gender': 0, 'id': 1062463, 'name': 'Rhian Sheehan', 'order': 76}
{'cast_id': 97, 'character': "Col. Quaritch's Mech Suit (uncredited)", 'credit_id': '52fe48019251416c750acb5b', 'gender': 0, 'id': 60656, 'name': 'T. J. Storm', 'order': 77}
{'cast_id': 98, 'character': 'Female Marine (uncredited)', 'credit_id': '52fe48019251416c750acb5f', 'gender': 0, 'id': 1207291, 'name': 'Jodie Taylor', 'order': 78}
{'cast_id': 99, 'character': 'Ikran Clan Leader (uncredited)', 'credit_id': '52fe48019251416c750acb63', 'gender': 1, 'id': 1186027, 'name': 'Alicia Vela-Bailey', 'order': 79}
{'cast_id': 100, 'character': 'Geologist (uncredited)', 'credit_id': '52fe48019251416c750acb67', 'gender': 0, 'id': 1207292, 'name': 'Richard Whiteside', 'order': 80}
{'cast_id': 101, 'character': "Na'vi (uncredited)", 'credit_id': '52fe48019251416c750acb6b', 'gender': 0, 'id': 103259, 'name': 'Nikie Zambo', 'order': 81}
{'cast_id': 102, 'character': 'Ambient Room Tech / Troupe', 'credit_id': '52fe48019251416c750acb6f', 'gender': 1, 'id': 42286, 'name': 'Julene Renee', 'order': 82}

In [92]:
def convert_cast(obj):
    l = []
    obj = ast.literal_eval(obj)
    counter = 0
    for cast in obj:
        if(counter != 3):
            l.append(cast['name'])
            counter += 1
        else:
            break

    return l

In [93]:
movies['cast'] = movies['cast'].apply(convert_cast)

In [94]:
for i in movies['cast']:
    print(i)

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']
['Johnny Depp', 'Orlando Bloom', 'Keira Knightley']
['Daniel Craig', 'Christoph Waltz', 'Léa Seydoux']
['Christian Bale', 'Michael Caine', 'Gary Oldman']
['Taylor Kitsch', 'Lynn Collins', 'Samantha Morton']
['Tobey Maguire', 'Kirsten Dunst', 'James Franco']
['Zachary Levi', 'Mandy Moore', 'Donna Murphy']
['Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo']
['Daniel Radcliffe', 'Rupert Grint', 'Emma Watson']
['Ben Affleck', 'Henry Cavill', 'Gal Gadot']
['Brandon Routh', 'Kevin Spacey', 'Kate Bosworth']
['Daniel Craig', 'Olga Kurylenko', 'Mathieu Amalric']
['Johnny Depp', 'Orlando Bloom', 'Keira Knightley']
['Johnny Depp', 'Armie Hammer', 'William Fichtner']
['Henry Cavill', 'Amy Adams', 'Michael Shannon']
['Ben Barnes', 'William Moseley', 'Anna Popplewell']
['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo']
['Johnny Depp', 'Penélope Cruz', 'Ian McShane']
['Will Smith', 'Tommy Lee Jones', 'Josh Brolin']
['Martin Freeman', 'Ian McKellen', 'Richard Armitage']
['Andrew Garfield', 'Emma Stone', 'Rhys Ifans']
['Russell Crowe', 'Cate Blanchett', 'Max von Sydow']
['Martin Freeman', 'Ian McKellen', 'Richard Armitage']
['Dakota Blue Richards', 'Nicole Kidman', 'Daniel Craig']
['Naomi Watts', 'Jack Black', 'Adrien Brody']
['Kate Winslet', 'Leonardo DiCaprio', 'Frances Fisher']
['Chris Evans', 'Robert Downey Jr.', 'Scarlett Johansson']
['Taylor Kitsch', 'Alexander Skarsgård', 'Rihanna']
['Chris Pratt', 'Bryce Dallas Howard', 'Irrfan Khan']
['Daniel Craig', 'Judi Dench', 'Javier Bardem']
['Tobey Maguire', 'Kirsten Dunst', 'James Franco']
['Robert Downey Jr.', 'Gwyneth Paltrow', 'Don Cheadle']
['Mia Wasikowska', 'Johnny Depp', 'Anne Hathaway']
['Hugh Jackman', 'Halle Berry', 'Ian McKellen']
['Billy Crystal', 'John Goodman', 'Steve Buscemi']
['Shia LaBeouf', 'Megan Fox', 'Josh Duhamel']
['Mark Wahlberg', 'Stanley Tucci', 'Kelsey Grammer']
['James Franco', 'Mila Kunis', 'Rachel Weisz']
['Andrew Garfield', 'Emma Stone', 'Jamie Foxx']
['Garrett Hedlund', 'Jeff Bridges', 'Olivia Wilde']
['Owen Wilson', 'Larry the Cable Guy', 'Michael Caine']
['Ryan Reynolds', 'Blake Lively', 'Peter Sarsgaard']
['Tom Hanks', 'Tim Allen', 'Ned Beatty']
['Christian Bale', 'Sam Worthington', 'Anton Yelchin']
['Vin Diesel', 'Paul Walker', 'Dwayne Johnson']
['Brad Pitt', 'Mireille Enos', 'Abigail Hargrove']
['Hugh Jackman', 'James McAvoy', 'Michael Fassbender']
['Chris Pine', 'Zachary Quinto', 'Zoe Saldana']
['Nicholas Hoult', 'Eleanor Tomlinson', 'Ewan McGregor']
['Leonardo DiCaprio', 'Tobey Maguire', 'Carey Mulligan']
['Jake Gyllenhaal', 'Gemma Arterton', 'Ben Kingsley']
['Idris Elba', 'Charlie Hunnam', 'Charlie Day']
['Shia LaBeouf', 'John Malkovich', 'Ken Jeong']
['Harrison Ford', 'Cate Blanchett', 'Shia LaBeouf']
['Raymond Ochoa', 'Jack Bright', 'Jeffrey Wright']
['Kelly Macdonald', 'Julie Walters', 'Billy Connolly']
['Chris Pine', 'Zachary Quinto', 'Karl Urban']
['Ben Burtt', 'Elissa Knight', 'Jeff Garlin']
['Chris Tucker', 'Jackie Chan', 'Hiroyuki Sanada']
['John Cusack', 'Amanda Peet', 'Chiwetel Ejiofor']
['Gary Oldman', 'Jim Carrey', 'Steve Valentine']
['Mila Kunis', 'Channing Tatum', 'Sean Bean']
['Alexander Skarsgård', 'Margot Robbie', 'Christoph Waltz']
['William Moseley', 'Anna Popplewell', 'Skandar Keynes']
['James McAvoy', 'Michael Fassbender', 'Jennifer Lawrence']
['Christian Bale', 'Heath Ledger', 'Aaron Eckhart']
['Ed Asner', 'Christopher Plummer', 'Jordan Nagai']
['Seth Rogen', 'Reese Witherspoon', 'Hugh Laurie']
['Robert Downey Jr.', 'Terrence Howard', 'Jeff Bridges']
['Ben Kingsley', 'Sacha Baron Cohen', 'Asa Butterfield']
['Will Smith', 'Kevin Kline', 'Kenneth Branagh']
['Brendan Fraser', 'Jet Li', 'John Hannah']
['Will Smith', 'Margot Robbie', 'Joel Kinnaman']
['Steve Carell', 'Lauren Graham', 'John Goodman']
['Tom Cruise', 'Emily Blunt', 'Brendan Gleeson']
['Kevin Costner', 'Chaim Girafi', 'Rick Aviles']
['Dennis Quaid', 'Channing Tatum', 'Marlon Wayans']
['Amy Poehler', 'Phyllis Smith', 'Richard Kind']
['Neel Sethi', 'Bill Murray', 'Ben Kingsley']
['Robert Downey Jr.', 'Gwyneth Paltrow', 'Don Cheadle']
['Kristen Stewart', 'Charlize Theron', 'Chris Hemsworth']
['Angelina Jolie', 'Elle Fanning', 'Sharlto Copley']
['Andy Serkis', 'Jason Clarke', 'Gary Oldman']
['Josh Hartnett', 'Simone Kessell', 'Tamsin Egerton']
['Keanu Reeves', 'Hiroyuki Sanada', 'Kou Shibasaki']
['Chris Evans', 'Samuel L. Jackson', 'Scarlett Johansson']
['Mike Myers', 'Eddie Murphy', 'Cameron Diaz']
['Britt Robertson', 'George Clooney', 'Raffey Cassidy']
['Scott Adsit', 'Ryan Potter', 'Daniel Henney']
['John C. Reilly', 'Sarah Silverman', 'Jack McBrayer']
['Tom Hanks', 'Michael Jeter', 'Nona Gaye']
['Liam Hemsworth', 'Jeff Goldblum', 'Bill Pullman']
['Jay Baruchel', 'Gerard Butler', 'Craig Ferguson']
['Arnold Schwarzenegger', 'Nick Stahl', 'Claire Danes']
['Chris Pratt', 'Zoe Saldana', 'Dave Bautista']
['Matthew McConaughey', 'Jessica Chastain', 'Anne Hathaway']
['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page']
['Hiroki Hasegawa', 'Yutaka Takenouchi', 'Satomi Ishihara']
['Ian McKellen', 'Martin Freeman', 'Richard Armitage']
['Paul Walker', 'Vin Diesel', 'Michelle Rodriguez']
['Cate Blanchett', 'Brad Pitt', 'Tilda Swinton']
['James McAvoy', 'Michael Fassbender', 'Jennifer Lawrence']
['Jennifer Lawrence', 'Josh Hutcherson', 'Liam Hemsworth']
['Nicolas Cage', 'Jay Baruchel', 'Monica Bellucci']
['Kurt Russell', 'Richard Dreyfuss', 'Josh Lucas']
['Johnny Depp', 'Mia Wasikowska', 'Anne Hathaway']
['Mike Myers', 'Eddie Murphy', 'Cameron Diaz']
['Paula Patton', 'Travis Fimmel', 'Ben Foster']
['Arnold Schwarzenegger', 'Jason Clarke', 'Emilia Clarke']
['Skandar Keynes', 'Georgie Henley', 'Simon Pegg']
['Ben Affleck', 'Josh Hartnett', 'Kate Beckinsale']
['Shia LaBeouf', 'Josh Duhamel', 'Megan Fox']
['Colin Farrell', 'Angelina Jolie', 'Val Kilmer']
['Daniel Radcliffe', 'Rupert Grint', 'Emma Watson']
['Daniel Radcliffe', 'Rupert Grint', 'Emma Watson']
['Will Smith', 'Charlize Theron', 'Jason Bateman']
['Will Smith', 'Alice Braga', 'Charlie Tahan']
['Johnny Depp', 'Freddie Highmore', 'David Kelly']
['Patton Oswalt', 'Ian Holm', 'Lou Romano']
['Christian Bale', 'Michael Caine', 'Liam Neeson']
['Ben Stiller', 'Jada Pinkett Smith', 'David Schwimmer']
['Ben Stiller', 'Amy Adams', 'Owen Wilson']
['Hugh Jackman', 'Liev Schreiber', 'Danny Huston']
['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss']
['Kristen Bell', 'Idina Menzel', 'Jonathan Groff']
['Keanu Reeves', 'Carrie-Anne Moss', 'Laurence Fishburne']
['Chris Hemsworth', 'Natalie Portman', 'Tom Hiddleston']
['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult']
['Tom Hanks', 'Ewan McGregor', 'Ayelet Zurer']
['Chris Hemsworth', 'Natalie Portman', 'Tom Hiddleston']
['John Travolta', 'Miley Cyrus', 'Susie Essman']
['Sam Rockwell', 'Penélope Cruz', 'Tracy Morgan']
['Sam Worthington', 'Liam Neeson', 'Ralph Fiennes']
['Johnny Depp', 'Michelle Pfeiffer', 'Helena Bonham Carter']
['Tom Cruise', 'Rebecca Ferguson', 'Simon Pegg']
['Benicio del Toro', 'Anthony Hopkins', 'Emily Blunt']
['Jerry Seinfeld', 'Renée Zellweger', 'Jim Cummings']
['Jack Black', 'Angelina Jolie', 'Dustin Hoffman']
['Noah Ringer', 'Nicola Peltz', 'Jackson Rathbone']
['Tom Cruise', 'Philip Seymour Hoffman', 'Ving Rhames']
['Channing Tatum', 'Jamie Foxx', 'Joey King']
['Seth Green', 'Joan Cusack', 'Dan Fogler']
['Hugh Jackman', 'Kate Winslet', 'Ian McKellen']
['Levi Miller', 'Garrett Hedlund', 'Hugh Jackman']
['Ty Burrell', 'Max Charles', 'Ariel Winter']
['Brad Pitt', 'Orlando Bloom', 'Eric Bana']
['Ben Stiller', 'Sacha Baron Cohen', 'David Schwimmer']
['Pierce Brosnan', 'Halle Berry', 'Rosamund Pike']
['Melissa McCarthy', 'Kristen Wiig', 'Kate McKinnon']
['Bruce Willis', 'Billy Bob Thornton', 'Ben Affleck']
['Tommy Lee Jones', 'Will Smith', 'Rip Torn']
['Ray Winstone', 'Angelina Jolie', 'Anthony Hopkins']
['Jack Black', 'Bryan Cranston', 'Dustin Hoffman']
['Tom Cruise', 'Jeremy Renner', 'Simon Pegg']
['Chris Pine', 'Alec Baldwin', 'Jude Law']
['Jim Carrey', 'Téa Leoni', 'Alec Baldwin']
['Tom Cruise', 'Ken Watanabe', 'William Atherton']
['Christian Bale', 'Joel Edgerton', 'John Turturro']
['Chris Pine', 'Zachary Quinto', 'Leonard Nimoy']
['Tobey Maguire', 'Willem Dafoe', 'Kirsten Dunst']
['Jay Baruchel', 'Gerard Butler', 'Kristen Wiig']
['Brenton Thwaites', 'Nikolaj Coster-Waldau', 'Gerard Butler']
['Josh Lucas', 'Jessica Biel', 'Jamie Foxx']
['Malin Åkerman', 'Billy Crudup', 'Carla Gugino']
['Mel Gibson', 'Danny Glover', 'Joe Pesci']
['Eric Bana', 'Jennifer Connelly', 'Sam Elliott']
['Dwayne Johnson', 'D.J. Cotrona', 'Adrianne Palicki']
['Matthew McConaughey', 'Penélope Cruz', 'Steve Zahn']
['Donald Sutherland', 'Ming-Na Wen', 'Alec Baldwin']
['Chris Evans', 'Hugo Weaving', 'Tommy Lee Jones']
['Pierce Brosnan', 'Sophie Marceau', 'Robert Carlyle']
['Russell Crowe', 'Paul Bettany', "James D'Arcy"]
['Kristen Stewart', 'Robert Pattinson', 'Taylor Lautner']
['Elijah Wood', 'Robin Williams', 'Pink']
['Edward Norton', 'Liv Tyler', 'Tim Roth']
['Ruby Barnhill', 'Mark Rylance', 'Rebecca Hall']
['Leonardo DiCaprio', 'Tom Hardy', 'Will Poulter']
['Ryan Reynolds', 'Paul Giamatti', 'Michael Peña']
['Johnny Depp', 'Isla Fisher', 'Ned Beatty']
['Tom McGrath', 'Chris Miller', 'Christopher Knights']
['Matt Damon', 'Julia Stiles', 'David Strathairn']
['Jack Black', 'Dustin Hoffman', 'Angelina Jolie']
['Paul Rudd', 'Michael Douglas', 'Evangeline Lilly']
['Jennifer Lawrence', 'Josh Hutcherson', 'Liam Hemsworth']
['Jim Parsons', 'Rihanna', 'Steve Martin']
['Tom Cruise', 'Dakota Fanning', 'Miranda Otto']
['Martin Lawrence', 'Will Smith', 'Jordi Mollà']
['Antonio Banderas', 'Salma Hayek', 'Zach Galifianakis']
['Angelina Jolie', 'Liev Schreiber', 'Chiwetel Ejiofor']
['Russell Crowe', 'Jennifer Connelly', 'Emma Watson']
['Jamie Bell', 'Andy Serkis', 'Daniel Craig']
['Daniel Radcliffe', 'Rupert Grint', 'Emma Watson']
['Nicole Kidman', 'Hugh Jackman', 'Essie Davis']
['Jaden Smith', 'Will Smith', 'Sophie Okonedo']
['D. B. Sweeney', 'Alfre Woodard', 'Ossie Davis']
['Ben Stiller', 'Rami Malek', 'Rebel Wilson']
['Will Ferrell', 'Brad Pitt', 'Tina Fey']
['Daniel Radcliffe', 'Rupert Grint', 'Emma Watson']
['Jeff Bridges', 'Ryan Reynolds', 'Kevin Bacon']
['Johnny Depp', 'Geoffrey Rush', 'Orlando Bloom']
['Jennifer Lawrence', 'Josh Hutcherson', 'Liam Hemsworth']
['Tom Hanks', 'Audrey Tautou', 'Ian McKellen']
['Jesse Eisenberg', 'Anne Hathaway', 'Leslie Mann']
['Patrick Stewart', 'Hugh Jackman', 'Ian McKellen']
['Vin Diesel', 'Paul Walker', 'Jordana Brewster']
['Robert Downey Jr.', 'Jude Law', 'Jared Harris']
['Sam Worthington', 'Liam Neeson', 'Ralph Fiennes']
['Arnold Schwarzenegger', 'Sharon Stone', 'Rachel Ticotin']
['Antonio Banderas', 'Vladimir Kulich', 'Dennis Storhøi']
['Jeremy Renner', 'Rachel Weisz', 'Edward Norton']
['George Clooney', "Chris O'Donnell", 'Arnold Schwarzenegger']
['Jim Carrey', 'Taylor Momsen', 'Jeffrey Tambor']
['Dennis Quaid', 'Jake Gyllenhaal', 'Emmy Rossum']
['Tom Cruise', 'Dougray Scott', 'Thandie Newton']
['George Clooney', 'Mark Wahlberg', 'Diane Lane']
['Ioan Gruffudd', 'Jessica Alba', 'Chris Evans']
['Suraj Sharma', 'Irrfan Khan', 'Ayush Tandon']
['Nicolas Cage', 'Eva Mendes', 'Wes Bentley']
['Matt Damon', 'Alicia Vikander', 'Tommy Lee Jones']
['Cameron Diaz', 'Drew Barrymore', 'Lucy Liu']
['Noomi Rapace', 'Michael Fassbender', 'Guy Pearce']
['Michael J. Fox', 'Geena Davis', 'Hugh Laurie']
['Matt Damon', 'Jodie Foster', 'Sharlto Copley']
['Vin Diesel', 'Thandie Newton', 'Karl Urban']
['Joel Kinnaman', 'Gary Oldman', 'Michael Keaton']
['Emile Hirsch', 'Christina Ricci', 'Matthew Fox']
['Reese Witherspoon', 'Paul Rudd', 'Owen Wilson']
['Tom Cruise', 'Cameron Diaz', 'Peter Sarsgaard']
['Tom Cruise', 'Morgan Freeman', 'Olga Kurylenko']
['Ewan McGregor', 'Natalie Portman', 'Hayden Christensen']
['Ewan McGregor', 'Natalie Portman', 'Hayden Christensen']
['John Goodman', 'Billy Crystal', 'Mary Gibbs']
['Hugh Jackman', 'Hiroyuki Sanada', 'Famke Janssen']
['Liam Neeson', 'Ewan McGregor', 'Natalie Portman']
['Nicolas Cage', 'Emma Stone', 'Ryan Reynolds']
['Clovis Cornillac', 'Gérard Depardieu', 'Franck Dubosc']
['Nicolas Cage', 'Adam Beach', 'Peter Stormare']
['Chris Hemsworth', 'Charlize Theron', 'Emily Blunt']
['Megan Fox', 'Will Arnett', 'William Fichtner']
['Sandra Bullock', 'George Clooney', 'Ed Harris']
['Pierce Brosnan', 'Linda Hamilton', 'Jamie Renée Smith']
['Megan Fox', 'Stephen Amell', 'Will Arnett']
['Miles Teller', 'Kate Mara', 'Michael B. Jordan']
['Ben Stiller', 'Jake Cherry', 'Carla Gugino']
['Dwayne Johnson', 'Alexandra Daddario', 'Carla Gugino']
['Pierce Brosnan', 'Jonathan Pryce', 'Michelle Yeoh']
['Mel Gibson', 'Heath Ledger', 'Joely Richardson']
['George Clooney', 'Brad Pitt', 'Catherine Zeta-Jones']
['Angelina Jolie', 'Brad Pitt', 'Vince Vaughn']
['Shailene Woodley', 'Theo James', 'Kate Winslet']
['Leonardo DiCaprio', 'Cate Blanchett', 'Kate Beckinsale']
['Jack Black', 'Amanda Peet', 'Emily Blunt']
['Seth Rogen', 'Jay Chou', 'Christoph Waltz']
['Sullivan Stapleton', 'Eva Green', 'Lena Headey']
['Hank Azaria', 'Neil Patrick Harris', 'Jayma Mays']
['Roseanne Barr', 'Judi Dench', 'Jennifer Tilly']
['Shailene Woodley', 'Theo James', 'Zoë Kravitz']
['Hugh Jackman', 'Dakota Goyo', 'Evangeline Lilly']
['Hank Azaria', 'Neil Patrick Harris', 'Brendan Gleeson']
['Sandra Bullock', 'Jason Patric', 'Willem Dafoe']
['Asa Butterfield', 'Harrison Ford', 'Hailee Steinfeld']
['Bruce Willis', 'Justin Long', 'Timothy Olyphant']
['Elijah Wood', 'Ian McKellen', 'Cate Blanchett']
['Jackie Chan', 'Steve Coogan', 'Cécile de France']
['Will Smith', 'Jamie Foxx', 'Jon Voight']
['Mike Myers', 'Dakota Fanning', 'Spencer Breslin']
['Will Smith', 'Bridget Moynahan', 'Alan Tudyk']
['Orlando Bloom', 'Eva Green', 'Jeremy Irons']
['Michael J. Fox', 'Geena Davis', 'Hugh Laurie']
['Anika Noni Rose', 'Bruno Campos', 'Keith David']
['Matt Damon', 'Jessica Chastain', 'Kristen Wiig']
['Ewan McGregor', 'Scarlett Johansson', 'Djimon Hounsou']
['Warren Beatty', 'Diane Keaton', 'Goldie Hawn']
['Nicolas Cage', 'Angelina Jolie', 'Giovanni Ribisi']
['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen']
['Tom Cruise', 'Colin Farrell', 'Samantha Morton']
['Daniel Radcliffe', 'Rupert Grint', 'Emma Watson']
['Daniel Craig', 'Eva Green', 'Mads Mikkelsen']
['Mark Wahlberg', 'Tim Roth', 'Helena Bonham Carter']
['Arnold Schwarzenegger', 'Linda Hamilton', 'Robert Patrick']
['Christian Bale', 'Johnny Depp', 'Giovanni Ribisi']
['Denzel Washington', 'Russell Crowe', 'Chiwetel Ejiofor']
['Arnold Schwarzenegger', 'Jamie Lee Curtis', 'Tom Arnold']
['Denzel Washington', 'John Travolta', 'Luis Guzmán']
['Robert De Niro', 'Ben Stiller', 'Owen Wilson']
['Will Ferrell', 'Mark Wahlberg', 'Eva Mendes']
['Arnold Schwarzenegger', 'James Caan', 'Vanessa Williams']
['Jamie Foxx', 'Christoph Waltz', 'Leonardo DiCaprio']
['Tom Hulce', 'Demi Moore', 'Tony Jay']
['David Spade', 'John Goodman', 'Eartha Kitt']
['Sylvester Stallone', 'Jason Statham', 'Dolph Lundgren']
['Nicolas Cage', 'Diane Kruger', 'Justin Bartha']
['Ed Speleers', 'Jeremy Irons', 'Sienna Guillory']
['Max Records', 'Catherine Keener', 'Lauren Ambrose']
['Josh Hutcherson', 'Amanda Seyfried', 'Colin Farrell']
['Johnny Depp', 'Angelina Jolie', 'Paul Bettany']
['Arnold Schwarzenegger', 'Gabriel Byrne', 'Kevin Pollak']
['Leonardo DiCaprio', 'Djimon Hounsou', 'Jennifer Connelly']
['Leonardo DiCaprio', 'Jonah Hill', 'Margot Robbie']
['Val Kilmer', 'Tommy Lee Jones', 'Jim Carrey']
['Casper Van Dien', 'Dina Meyer', 'Denise Richards']
['Tom Hanks', 'Halle Berry', 'Jim Broadbent']
['Emily Barclay', 'Abbie Cornish', 'Essie Davis']
['Halle Berry', 'Benjamin Bratt', 'Sharon Stone']
['Dwayne Johnson', 'Ian McShane', 'John Hurt']
['Joseph Gordon-Levitt', 'Brian Murray', 'David Hyde Pierce']
['Will Ferrell', 'Anna Friel', 'Danny McBride']
['Sylvester Stallone', 'Jason Statham', 'Harrison Ford']
['Edgar Ramírez', 'Luke Bracey', 'Teresa Palmer']
['Jamie Kennedy', 'Alan Cumming', 'Traylor Howard']
['Chris Hemsworth', 'Benjamin Walker', 'Cillian Murphy']
['Eddie Murphy', 'Randy Quaid', 'Rosario Dawson']
['Matt Damon', 'Greg Kinnear', 'Brendan Gleeson']
['Noah Schnapp', 'Bill Melendez', 'Venus Schultheis']
['Steve Martin', 'Campbell Scott', 'Ben Gazzara']
['Brendan Fraser', 'Rachel Weisz', 'John Hannah']
['Leonardo DiCaprio', 'Daniel Day-Lewis', 'Cameron Diaz']
['Christian Bale', 'Ni Ni', 'Tong Dawei']
['Shia LaBeouf', 'Jeff Bridges', 'Zooey Deschanel']
['Nicole Kidman', 'Matthew Broderick', 'Bette Midler']
['Josh Hartnett', 'Ewan McGregor', 'Jason Isaacs']
['Will Ferrell', 'Zach Galifianakis', 'Dylan McDermott']
['Bruce Willis', 'Gary Oldman', 'Ian Holm']
['Sarah Jessica Parker', 'Kristin Davis', 'Cynthia Nixon']
['Kenneth Branagh', 'Kevin Kline', 'Rosie Perez']
['John Leguizamo', 'Ray Romano', 'Chris Wedge']
['Lily James', 'Cate Blanchett', 'Richard Madden']
['Rachel Weisz', 'Mark Wahlberg', 'Susan Sarandon']
['Albert Brooks', 'Ellen DeGeneres', 'Alexander Gould']
['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen']
['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen']
['Jeff Bridges', 'Julianne Moore', 'Ben Barnes']
['Angelina Jolie', 'Jon Voight', 'Iain Glen']
['Johnny Depp', 'Paul Bettany', 'Rebecca Hall']
['Sam Neill', 'William H. Macy', 'Téa Leoni']
['James Franco', 'Freida Pinto', 'John Lithgow']
['Freddie Highmore', 'Mary-Louise Parker', 'Nick Nolte']
['Bruce Willis', 'Jai Courtney', 'Sebastian Koch']
['Dennis Quaid', 'Billy Bob Thornton', 'Jason Patric']
['Craig T. Nelson', 'Holly Hunter', 'Samuel L. Jackson']
['Geena Davis', 'Matthew Modine', 'Frank Langella']
['Logan Lerman', 'Brandon T. Jackson', 'Alexandra Daddario']
['Tommy Lee Jones', 'Will Smith', 'Linda Fiorentino']
['Tom Hanks', 'Tim Allen', 'Joan Cusack']
['Denzel Washington', 'Chris Pine', 'Rosario Dawson']
['Chris Tucker', 'Jackie Chan', 'Zhang Ziyi']
['Harrison Ford', 'Michelle Pfeiffer', 'Diana Scarwid']
['Bill Hader', 'Anna Faris', 'James Caan']
['Ray Romano', 'John Leguizamo', 'Denis Leary']
['Ben Stiller', 'Kristen Wiig', 'Patton Oswalt']
['Cameron Diaz', 'Lucy Liu', 'Drew Barrymore']
['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson']
['Eddie Murphy', 'Jackie Chan', 'Ming-Na Wen']
['Ben Stiller', 'Jack Black', 'Robert Downey Jr.']
['Daniel Craig', 'Rooney Mara', 'Christopher Plummer']
['Bruce Willis', 'Jeremy Irons', 'Samuel L. Jackson']
['Robert Downey Jr.', 'Jude Law', 'Rachel McAdams']
['Jack Huston', 'Toby Kebbell', 'Rodrigo Santoro']
['Michael J. Fox', 'Corey Burton', 'Claudia Christian']
['Jason Lee', 'Justin Long', 'Bella Thorne']
['Tom Cruise', 'Carice van Houten', 'Kenneth Branagh']
['Adam Sandler', 'John Turturro', 'Emmanuelle Chriqui']
['Adam Sandler', 'Michelle Monaghan', 'Peter Dinklage']
['Haley Joel Osment', "Frances O'Connor", 'Sam Robards']
['Eddie Murphy', 'Terence Stamp', 'Nathaniel Parker']
['Jodie Foster', 'Matthew McConaughey', 'James Woods']
['Kevin Bacon', 'Elisabeth Shue', 'Josh Brolin']
['Nicole Kidman', 'Sean Penn', 'Catherine Keener']
['Logan Lerman', 'Alexandra Daddario', 'Douglas Smith']
['Angelina Jolie', 'Gerard Butler', 'Noah Taylor']
['Jesse Eisenberg', 'Woody Harrelson', 'Mark Ruffalo']
['Val Kilmer', 'Elisabeth Shue', 'Rade Serbedzija']
['Robert Redford', 'Brad Pitt', 'Catherine McCormack']
['Gary Sinise', 'Tim Robbins', 'Don Cheadle']
['Jesse Eisenberg', 'Anne Hathaway', 'Leslie Mann']
['Robin Williams', 'Sam Neill', 'Embeth Davidtz']
['Tommy Lee Jones', 'Anne Heche', 'Gaby Hoffmann']
['Harrison Ford', 'Brad Pitt', 'Margaret Colin']
['Harrison Ford', 'Liam Neeson', 'Peter Sarsgaard']
['Arnold Schwarzenegger', 'James Earl Jones', 'Max von Sydow']
['Russell Crowe', 'Renée Zellweger', 'Paul Giamatti']
['Elle Fanning', 'Nathan Lane', 'John Turturro']
['Jeff Bridges', 'David McCullough', 'Chris Cooper']
['Helen Hunt', 'Bill Paxton', 'Cary Elwes']
['Tom Hanks', 'Helen Hunt', 'Chris Noth']
['Elijah Wood', 'Robin Williams', 'Brittany Murphy']
['Matt Damon', 'Franka Potente', 'Brian Cox']

In [95]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [119]:
def fetch_director(obj):
    l = []
    for i in ast.literal_eval(obj):
        if( i['job'] == 'Director'):
            l.append(i['name'])
            break
        
    return l

In [122]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [123]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]

In [124]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [126]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [127]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]

In [139]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [140]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [141]:
movies['tag'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [145]:
new_df = movies[['movie_id','title','tag']]

In [149]:
new_df['tag'] = new_df['tag'].apply(lambda x:" ".join(x))

C:\Users\Dell\AppData\Local\Temp\ipykernel_16340\2072057965.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag'] = new_df['tag'].apply(lambda x:" ".join(x))

In [150]:
new_df.head()

,movie_id,title,tag
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [151]:
new_df['tag'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [153]:
new_df['tag'] = new_df['tag'].apply(lambda x: x.lower())

C:\Users\Dell\AppData\Local\Temp\ipykernel_16340\3706803269.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag'] = new_df['tag'].apply(lambda x: x.lower())

In [154]:
new_df.head(3)

,movie_id,title,tag
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...